# Generated by Django 4.1.13 on 2024-04-12 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0009_datasetmetadata_units_datasetmetadata_units_short"),
        ("users", "0003_allowlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("aggregation_period", models.CharField(max_length=255)),
                ("correlation_metric", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndexDataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("weight", models.FloatField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datasets.datasetmetadata",
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.index"
                    ),
                ),
            ],
        ),
    ]
